# Generated by Django 2.2 on 2019-04-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problemsbyuser',
            name='number',
            field=models.IntegerField(),
        ),
    ]
