# Generated by Django 2.2 on 2019-04-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('exTestCaseInput', models.TextField(verbose_name='exampleTestCaseInput')),
                ('exTestCaseOutput', models.TextField(verbose_name='exampleTestCaseOutput')),
                ('serverTestCaseInput', models.TextField()),
                ('serverTestCaseOutput', models.TextField()),
                ('numOfTry', models.IntegerField()),
                ('numOfRight', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
                ('answerFile', models.FileField(upload_to='')),
            ],
        ),
    ]
