# Generated by Django 2.2 on 2019-04-30 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='numOfRight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='problem',
            name='numOfTry',
            field=models.IntegerField(default=0),
        ),
    ]
