# Generated by Django 2.2 on 2019-05-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problem', '0002_auto_20190430_2346'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='ratio',
            field=models.FloatField(default=0),
        ),
    ]
